version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  helloworld_project:
    image: my_django_app:07
    environment:
      DB_NAME: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'your_password'
      DB_HOST: 'db'
      DB_PORT: 5432
    volumes:
      - helloworld_data:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
      - static_volume:/app/static
    depends_on:
      - helloworld_project

volumes:
  postgres_data:
  helloworld_data:
  static_volume:

